# Generated by Django 4.2.4 on 2023-08-11 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('num_tables', models.PositiveIntegerField()),
                ('num_rows', models.PositiveIntegerField()),
                ('num_columns', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PdfTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.pdffile')),
            ],
        ),
    ]
